### ISSUE TITLE
Mod does not work at all for anyone

### ISSUE THREAD

**Issue by Johnlongears** [Skippeh/Oxide.GettingOverItMP#31]
The mod has not been working for me or for my friends for the past couple of days. When I open the server browser, no servers show up at all. Creating a server does not work, and has not worked since I got the game a few weeks ago. There used to be servers called Degenerate Server for Theives and Codyumm's Server (the latter of which didn't even work), but they don't even show up in the server list anymore.

**Comment by Superfech** [comment]
Was This Mod Abandoned?

**Comment by Johnlongears** [comment]
No, it magically fixed itself a couple of days ago
