### ISSUE TITLE
Hi there, where is the official build to download?

### ISSUE THREAD

**Issue by 411752230** [Skippeh/Oxide.GettingOverItMP#7]
I found the page was redirected to another site. But didnt see any mod concerning GOIMP

**Comment by Skippeh** [comment]
Currently the only source is the discord server.

https://discord.gg/msxx6Vr
Here's a direct link too in case you don't want to join:
Client: https://cdn.discordapp.com/attachments/399867244416335872/667451495708491776/goimp-client-0.6.2_1.5861.zip
Server: https://cdn.discordapp.com/attachments/399867244416335872/667439588931010560/goimp-server-0.1.4.zip
